image: $CI_REGISTRY/docker/maven-coingi:master

stages:
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build_snapshot:
  stage: build
  cache:
    key: build_snapshot
    paths:
      - .m2/repository
  only:
    - master
  except:
    - tags
  tags:
    - docker
  script:
    - mvn -B deploy $COINGI_MAVEN_DEPLOY_PARAMETER

build_release:
  stage: build
  cache:
      key: build_release
      paths:
        - .m2/repository
  only:
    - tags
  tags:
    - docker
  script:
    - mvn -B deploy -P release $COINGI_MAVEN_DEPLOY_PARAMETER
